server:
  port: @server.port@
#  servlet:
#    context-path: /apis/professional
spring:
  application:
    name: @project.artifactId@
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    filters: stat,wall
    url: @db.url@
    username: @db.username@
    password: @db.password@
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect     #不加这句则默认为myisam引擎
  #  security:
  #    user:
  #      name: user
  #      password: 123456
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: dengyong
    password: dengyong
    virtual-host: /dengyong
#  kafka:
#    bootstrap-servers: 192.168.169.20:9092
#    producer:
#      batch-size: 16785                         #一次最多发送数据量
#      retries: 1                                #发送失败后的重复发送次数
#      buffer-memory: 33554432                   #32M批处理缓冲区
#      linger: 1                                 #提交延时 当达到指定时间后  生产者将消息提交给kafka
#    consumer:
#      group-id: dengyong_topic
#      auto-offset-reset: latest                 #最早未被消费的offset earliest
#      max-poll-records: 50                      #批量消费一次最大拉取的数据量
#      enable-auto-commit: false                 #是否开启自动提交
#      auto-commit-interval: 1000                #自动提交的间隔时间
#      session-timeout: 20000                    #连接超时时间
#      max-poll-interval: 15000                  #手动提交设置与poll的心跳数,如果消息队列中没有消息，等待毫秒后，调用poll()方法。如果队列中有消息，立即消费消息，每次消费的消息的多少可以通过max.poll.records配置。
#      max-partition-fetch-bytes: 15728640       #设置拉取数据的大小,15M
#    listener:
#      batch-listener: true                      #是否开启批量消费，true表示批量消费
#      concurrencys: 3,6                         #设置消费的线程数
#      poll-timeout: 1500                        #只限自动提交
#      missing-topics-fatal: false
info:
  app:
    name: @project.artifactId@
    description: @project.description@
    version: @project.version@
    encoding: @project.build.sourceEncoding@
    base-package: @project.groupId@.@project.artifactId@
    java:
      version: @java.version@

